export const TradingTooltips =[
    {
        titleShow: 'Show Trend Line',
        titleHide: 'Hide Trend Line',
        ariaLabel: 'Line',
        Svg: 'TraidingSvg',
        state: 'ShowTraid',
    },
    {
        titleShow: 'Show SAR',
        titleHide: 'Hide SAR',
        ariaLabel: 'SAR',
        Svg: 'DragIndicatorIcon',
        state: 'showSAR',
    },
    {
        titleShow: 'Show Line Serries',
        titleHide: 'Hide Line Serries',
        ariaLabel: 'Serries',
        Svg: 'TimelineIcon',
        state: 'showLineSerries',
    },
    {
        titleShow: 'show Line Bollinger',
        titleHide: 'Hide Line Bollinger',
        ariaLabel: 'Bollinger',
        Svg: 'FiberManualRecordIcon',
        state: 'showBollingerSeries',
    },
    {
        titleShow: 'Show Hover Tooltip',
        titleHide: 'Hide Hover Tooltip',
        ariaLabel: 'Line',
        Svg: 'SettingsEthernetIcon',
        state: 'HoverTooltipShow',
    },
    {
        titleShow: 'OHLC series',
        titleHide: 'Candle Series',
        ariaLabel: 'OHLC',
        Svg: 'WbIncandescentIcon',
        state: 'CandleView',
    },
    {
        titleShow: 'Show Bollinger',
        titleHide: 'Hide Bollinger',
        ariaLabel: 'Bollinger',
        Svg: 'BubbleChartIcon',
        state: 'showBollingerBandTooltip',
    },
    {
        titleShow: 'Show Average',
        titleHide: 'Hide Average',
        ariaLabel: 'Average',
        Svg: 'TrendingUpIcon',
        state: 'showMovingAverageTooltip',
    },
    {
        titleShow: 'Show OHLC',
        titleHide: 'Hide OHLC',
        ariaLabel: 'OHLC',
        Svg: 'AssessmentIcon',
        state: 'showOHLCTooltip',
    },
    {
        titleShow: 'Show MouseCoordinate',
        titleHide: 'Hide MouseCoordinate',
        ariaLabel: 'MouseCoordinate',
        Svg: 'MouseIcon',
        state: 'showMouseCoordinate',
    },
    {
        titleShow: 'Show Valume Table',
        titleHide: 'Hide Valume Table',
        ariaLabel: 'ValumeTableBarChart',
        Svg: 'EqualizerIcon',
        state: 'showBarChartVolume',
    },
    {
        titleShow: 'Show Area Valume Table',
        titleHide: 'Hide Area Valume Table',
        ariaLabel: 'ValumeTableAreaChart',
        Svg: 'InsertChartIcon',
        state: 'showAreaChartVolume',
        secondState: "showBarChartVolume"
    },
]