export const TradingTooltips =[
    {
        en_titleShow: 'Show Trend Line',
        cn_titleShow: '显示趋势线',
        en_titleHide: 'Hide Trend Line',
        cn_titleHide: '隐藏趋势线',
        ariaLabel: 'Line',
        Svg: 'TraidingSvg',
        state: 'ShowTraid',
    },
    {
        en_titleShow: 'Show SAR',
        cn_titleShow: '显示SAR',
        en_titleHide: 'Hide SAR',
        cn_titleHide: '隐藏SAR',
        ariaLabel: 'SAR',
        Svg: 'DragIndicatorIcon',
        state: 'showSAR',
    },
    {
        en_titleShow: 'Show Line Series',
        cn_titleShow: '表演线系列',
        en_titleHide: 'Hide Line Series',
        cn_titleHide: '皮线系列',
        ariaLabel: 'Serries',
        Svg: 'TimelineIcon',
        state: 'showLineSerries',
    },
    {
        en_titleShow: 'show Line Bollinger',
        cn_titleShow: '显示Line Bollinger',
        en_titleHide: 'Hide Line Bollinger',
        cn_titleHide: '隐藏线布林格',
        ariaLabel: 'Bollinger',
        Svg: 'FiberManualRecordIcon',
        state: 'showBollingerSeries',
    },
    {
        en_titleShow: 'Show Hover Tooltip',
        cn_titleShow: '显示悬停工具提示',
        en_titleHide: 'Hide Hover Tooltip',
        cn_titleHide: '隐藏悬停工具提示',
        ariaLabel: 'Line',
        Svg: 'SettingsEthernetIcon',
        state: 'HoverTooltipShow',
    },
    {
        en_titleShow: 'OHLC series',
        cn_titleShow: 'OHLC系列',
        en_titleHide: 'Candle Series',
        cn_titleHide: '蜡烛系列',
        ariaLabel: 'OHLC',
        Svg: 'WbIncandescentIcon',
        state: 'CandleView',
    },
    {
        en_titleShow: 'Show Bollinger',
        cn_titleShow: '显示布林格',
        en_titleHide: 'Hide Bollinger',
        cn_titleHide: '皮德·林格',
        ariaLabel: 'Bollinger',
        Svg: 'BubbleChartIcon',
        state: 'showBollingerBandTooltip',
    },
    {
        en_titleShow: 'Show Average',
        cn_titleShow: '显示平均值',
        en_titleHide: 'Hide Average',
        cn_titleHide: '隐藏平均',
        ariaLabel: 'Average',
        Svg: 'TrendingUpIcon',
        state: 'showMovingAverageTooltip',
    },
    {
        en_titleShow: 'Show OHLC',
        cn_titleShow: '显示OHLC',
        en_titleHide: 'Hide OHLC',
        cn_titleHide: '隐藏OHLC',
        ariaLabel: 'OHLC',
        Svg: 'AssessmentIcon',
        state: 'showOHLCTooltip',
    },
    {
        en_titleShow: 'Show Mouse Coordinate',
        cn_titleShow: '显示鼠标坐标',
        en_titleHide: 'Hide Mouse Coordinate',
        cn_titleHide: '隐藏鼠标坐标',
        ariaLabel: 'MouseCoordinate',
        Svg: 'MouseIcon',
        state: 'showMouseCoordinate',
    },
    {
        en_titleShow: 'Show Valume Table',
        cn_titleShow: '显示价值表',
        en_titleHide: 'Hide Valume Table',
        cn_titleHide: '隐藏估价表',
        ariaLabel: 'ValumeTableBarChart',
        Svg: 'EqualizerIcon',
        state: 'showBarChartVolume',
    },
    {
        en_titleShow: 'Show Area Valume Table',
        cn_titleShow: '显示区域体积表',
        en_titleHide: 'Hide Area Valume Table',
        cn_titleHide: '隐藏区域体积表',
        ariaLabel: 'ValumeTableAreaChart',
        Svg: 'InsertChartIcon',
        state: 'showAreaChartVolume',
        secondState: "showBarChartVolume"
    },
]